stopcovid19-okayama/covid19

package.json

disable pre-commit

---

pages/worker.vue

- close #30 
- #30 
- 雇用調整助成金の相談窓口について (岡山労働局) のリンクを変更しました

update: 雇用調整助成金の相談窓口について (岡山労働局) のリンク変更

---

pages/about.vue

- close #24 
- close #28 
- #24 
- #28 
- 文言を有志のエンジニアに変更
- 貢献者の名前のハードコーディングをやめてCONTRIBUTERS.MDにリンクを張った

#24,#28の対応

---

layouts/default.vue
pages/cards/_card.vue

- close #44 
- #44 
- 当サイトは岡山県の新型コロナウイルス感染症 (COVID-19) に関する最新情報を提供するために、有志が開設したものです。に変更
なし

descriptionの変更

---

.github/workflows/deploy.yml
.github/workflows/develop.yml

- close #51 
- GitHub Actionの結果をSlackに通知 (development版)

GitHub Actionの結果をSlackに通知 (development版)

---

components/DataView.vue

- close #54
- #54
- 岡山用のTwitterハッシュタグを追加

Add hashtag stopcovid19-okayama/covid19#54

---

components/SideNavigation.vue

Fix menu title stopcovid19-okayama/covid19#57

---

pages/about.vue

- close #63 
- close #63 
- ソースコードについてのリンクを岡山県のものに変更しました

update: ソースコードについてのリンクを岡山県のものに変更

---

components/SideNavigation.vue

Add social link

---

pages/about.vue

fixes #53
- close #53
- #53
- Issueの通りの連絡先を追加しました

update: add contact

---

.github/workflows/data.yml

- close #60
- #60 
- 毎日21時にデータ更新のPRを発行するGitHub Actionを追加

データ更新の半自動化

---

pages/about.vue

- close #83 
- #83 
- about.vueにディスカッションについての記載を追加

ディスカッションについての記載を追加

---

.github/workflows/data.yml
CONTRIBUTING.md

- close #104 
- データ更新のGitHub Actionの実行時間を21:15に修正
- データ更新のGitHub Actionを実行した際に生成されるブランチを修正

GitHub Actionの実行時刻とブランチの問題を修正

---

.github/workflows/ogp_builder.yml

- close #117 
- Branch Protectionのinclude administratorsを一時的に無効にする
- Branch Protectionのinclude administratorsを有効に戻す

OGP画像がアップロードされないバグを修正

---

components/ConfirmedCasesTable.vue
components/cards/ConfirmedCasesDetailsCard.vue
data/main_summary.json
pages/index.vue
utils/formatConfirmedCases.ts

検査陽性者の状況カードを追加

---

pages/cards/_card.vue

- close #125 
- コメントアウトされていたカードを元に戻した

fix cards (add details-of-confirmed-cases)

---

components/cards/SimpleNumberCard.vue

- close #127
- #127
- SimpleNumberCardコンポーネントを追加

Add: SimpleNumberCard

---

components/SideNavigation.vue
package-lock.json
package.json
yarn.lock

- close #128 
- Creative Commons CC-BY 4.0を付記しました。

CreativeCommons

---

components/SideNavigation.vue

- close #128 
- creative commonsの追加（再実装）

Add Creative-Commons

---

.github/workflows/deploy.yml

- close #146 
- deploy.ymlの移植ミスを修正

deploy.ymlの移植ミスを修正

---

components/WhatsNew.vue
data/news.json

- close #152 
- 緊急事態宣言についてのバナーを最新のお知らせに追加
- ニュースの更新

緊急事態宣言についてのバナーを最新のお知らせに追加 & ニュースの更新

---

components/DataView.vue
layouts/default.vue

- close #165
- #165
- ツイート内容を修正

Fix: Twitter share content

---

components/flow/FlowPcSuspect.vue
components/flow/FlowSpSuspect.vue

- close #177 
- #177 
- 新型コロナコールセンター対応時間更新
PC
SP

update: 新型コロナコールセンター対応時間更新

---

components/WhatsNew.vue

- close #190 
- 「岡山緊急事態宣言について」をクリックすると「お探しのページを見つけることはできませんでした」と表示されページが存在しない問題を別のリンクに置き換えることで解決（二枚目→三枚目に移行）

#190 「岡山緊急事態宣言について」のURLを修正

---

components/ConfirmedCasesDetailsTable.vue
data/main_summary.json
utils/formatConfirmedCases.ts

- close #220
- 検査陽性者の状況カードに入院調整中を追加

検査陽性者の状況カードに入院調整中を追加

---

yarn.lock

yan.lock の修正

---

.github/workflows/data.yml

Auto Merge Botを用いた、データ完全自動化の実現

---

components/ConfirmedCasesDetailsTable.vue
utils/formatConfirmedCases.ts

宿泊療養施設に入所中の行を追加

---

.github/workflows/ogp_builder.yml

Fix: OGP画像がアップロードされないバグ

---

components/SideNavigation.vue
pages/about.vue

協力団体・企業の追加

---

.github/workflows/data.yml
.github/workflows/i18n_generator.yml

- close #1737 
- data.yml, i18n_generate.yml の create-pull-request を v3 にアップデート

create-pull-request を v3 へアップデート

---

components/ActiveTokyoAlert.vue
components/SiteTopUpper.vue
components/TokyoAlertCard.vue
data/tokyo_alert.json

Add: 医療非常事態宣言

---

components/ActiveTokyoAlert.vue

- close #0
- close #0
- #0
- #0
- 医療非常事態宣言発令中にスタイルが当たっていない問題の修正

HotFix Tokyo Alert Unset Styles

---

pages/covid19.vue
pages/flow.vue

- close #0
- close #0
- #0
- #0
- xxxxxx
- xxx

Flowとcovid19ページデザイン崩れの暫定対応

---

nuxt.config.ts

fix: OGP設定のtypoと思われる部分を修正

---

.github/workflows/data.yml
.github/workflows/deploy.yml
.github/workflows/develop.yml

Remove slack notofication
